// This file was generated by counterfeiter
package usageeventsfakes

import (
	"sync"

	"github.com/cloudfoundry-community/firehose-to-syslog/caching"
	"github.com/pivotalservices/app-metrics-nozzle/usageevents"
)

type FakeCachedApp struct {
	GetAppByGUIDStub        func(appGUID string) []caching.App
	getAppByGUIDMutex       sync.RWMutex
	getAppByGUIDArgsForCall []struct {
		appGUID string
	}
	getAppByGUIDReturns struct {
		result1 []caching.App
	}
	GetAppInfoStub        func(appGUID string) caching.App
	getAppInfoMutex       sync.RWMutex
	getAppInfoArgsForCall []struct {
		appGUID string
	}
	getAppInfoReturns struct {
		result1 caching.App
	}
	GetAllAppStub        func() []caching.App
	getAllAppMutex       sync.RWMutex
	getAllAppArgsForCall []struct{}
	getAllAppReturns     struct {
		result1 []caching.App
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCachedApp) GetAppByGUID(appGUID string) []caching.App {
	fake.getAppByGUIDMutex.Lock()
	fake.getAppByGUIDArgsForCall = append(fake.getAppByGUIDArgsForCall, struct {
		appGUID string
	}{appGUID})
	fake.recordInvocation("GetAppByGUID", []interface{}{appGUID})
	fake.getAppByGUIDMutex.Unlock()
	if fake.GetAppByGUIDStub != nil {
		return fake.GetAppByGUIDStub(appGUID)
	} else {
		return fake.getAppByGUIDReturns.result1
	}
}

func (fake *FakeCachedApp) GetAppByGUIDCallCount() int {
	fake.getAppByGUIDMutex.RLock()
	defer fake.getAppByGUIDMutex.RUnlock()
	return len(fake.getAppByGUIDArgsForCall)
}

func (fake *FakeCachedApp) GetAppByGUIDArgsForCall(i int) string {
	fake.getAppByGUIDMutex.RLock()
	defer fake.getAppByGUIDMutex.RUnlock()
	return fake.getAppByGUIDArgsForCall[i].appGUID
}

func (fake *FakeCachedApp) GetAppByGUIDReturns(result1 []caching.App) {
	fake.GetAppByGUIDStub = nil
	fake.getAppByGUIDReturns = struct {
		result1 []caching.App
	}{result1}
}

func (fake *FakeCachedApp) GetAppInfo(appGUID string) caching.App {
	fake.getAppInfoMutex.Lock()
	fake.getAppInfoArgsForCall = append(fake.getAppInfoArgsForCall, struct {
		appGUID string
	}{appGUID})
	fake.recordInvocation("GetAppInfo", []interface{}{appGUID})
	fake.getAppInfoMutex.Unlock()
	if fake.GetAppInfoStub != nil {
		return fake.GetAppInfoStub(appGUID)
	} else {
		return fake.getAppInfoReturns.result1
	}
}

func (fake *FakeCachedApp) GetAppInfoCallCount() int {
	fake.getAppInfoMutex.RLock()
	defer fake.getAppInfoMutex.RUnlock()
	return len(fake.getAppInfoArgsForCall)
}

func (fake *FakeCachedApp) GetAppInfoArgsForCall(i int) string {
	fake.getAppInfoMutex.RLock()
	defer fake.getAppInfoMutex.RUnlock()
	return fake.getAppInfoArgsForCall[i].appGUID
}

func (fake *FakeCachedApp) GetAppInfoReturns(result1 caching.App) {
	fake.GetAppInfoStub = nil
	fake.getAppInfoReturns = struct {
		result1 caching.App
	}{result1}
}

func (fake *FakeCachedApp) GetAllApp() []caching.App {
	fake.getAllAppMutex.Lock()
	fake.getAllAppArgsForCall = append(fake.getAllAppArgsForCall, struct{}{})
	fake.recordInvocation("GetAllApp", []interface{}{})
	fake.getAllAppMutex.Unlock()
	if fake.GetAllAppStub != nil {
		return fake.GetAllAppStub()
	} else {
		return fake.getAllAppReturns.result1
	}
}

func (fake *FakeCachedApp) GetAllAppCallCount() int {
	fake.getAllAppMutex.RLock()
	defer fake.getAllAppMutex.RUnlock()
	return len(fake.getAllAppArgsForCall)
}

func (fake *FakeCachedApp) GetAllAppReturns(result1 []caching.App) {
	fake.GetAllAppStub = nil
	fake.getAllAppReturns = struct {
		result1 []caching.App
	}{result1}
}

func (fake *FakeCachedApp) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAppByGUIDMutex.RLock()
	defer fake.getAppByGUIDMutex.RUnlock()
	fake.getAppInfoMutex.RLock()
	defer fake.getAppInfoMutex.RUnlock()
	fake.getAllAppMutex.RLock()
	defer fake.getAllAppMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeCachedApp) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ usageevents.CachedApp = new(FakeCachedApp)
